### ISSUE TITLE
Display temperature

### ISSUE THREAD

**Issue by B-Chavez** [B-Chavez/weather-app#2]
## **Feature**

Display default temperature
## Motivation 
User needs to be able to view a default location
## Plan
Call the api with a default location, Los Angeles
## Wireframes
![user can choose location desktop](https://user-images.githubusercontent.com/59714905/116171321-6183f600-a6bd-11eb-91ec-8f66480d51d2.png)
![user can choose location mobile](https://user-images.githubusercontent.com/59714905/116171342-6e084e80-a6bd-11eb-801a-86fc2c7b88a3.png)
## Task List
- [x] Create UI
- [x] Add background
- [x] Call weather api with token and include zipcode/city name from text box on second page
- [x] Receive JSON
- [ ] Change weather location to `json.name`
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
