### ISSUE TITLE
Display humidity

### ISSUE THREAD

**Issue by B-Chavez** [B-Chavez/weather-app#4]
## Feature
Display default humidity

## Motivation
User needs to be able to view humidity

## Plan
Call the api and ask for the humidity 

## Task List

- [x]  Add <div> to UI.jsx to hold humidity
- [x]  Add weather data via this.state.weatherData to div

## Clean Up
- [x]  Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x]  Remove all console logs.
- [x]  Remove all commented out code.
- [x]  Remove all CSS properties that have no effect.
- [x]  Check all code for proper formatting and indentation.
- [x]  Confirm that there are no errors in the console while using the application.
- [x]  Confirm that all previous functionality still works without errors.
- [x]  Confirm that the user interface looks natural on both mobile and desktop screens.
- [x]  Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
